name: "multiple jobs"

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: windows-latest
    steps:
      - name: "Running on master/test push"
        run: echo "Running on Master push"

  on-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: windows-latest
    steps:
      - name: "Running on pull request"
        run: echo "Running on pull request"
