name: "Node.js CI/CD Pipeline"
on:
  push:
    branches:
      - main
      - master
jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      - name: "Check Node version"
        run: node --version
      - name: "Clone the Repository"
        uses: actions/checkout@v2
